# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/work/distribution_test/issue2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/work/distribution_test/issue2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/work/distribution_test/issue2/CMakeFiles /home/ubuntu/work/distribution_test/issue2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/work/distribution_test/issue2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

LockClient.o: LockClient.cpp.o

.PHONY : LockClient.o

# target to build an object file
LockClient.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/LockClient.cpp.o
.PHONY : LockClient.cpp.o

LockClient.i: LockClient.cpp.i

.PHONY : LockClient.i

# target to preprocess a source file
LockClient.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/LockClient.cpp.i
.PHONY : LockClient.cpp.i

LockClient.s: LockClient.cpp.s

.PHONY : LockClient.s

# target to generate assembly for a file
LockClient.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/LockClient.cpp.s
.PHONY : LockClient.cpp.s

LockServer.o: LockServer.cpp.o

.PHONY : LockServer.o

# target to build an object file
LockServer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/LockServer.cpp.o
.PHONY : LockServer.cpp.o

LockServer.i: LockServer.cpp.i

.PHONY : LockServer.i

# target to preprocess a source file
LockServer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/LockServer.cpp.i
.PHONY : LockServer.cpp.i

LockServer.s: LockServer.cpp.s

.PHONY : LockServer.s

# target to generate assembly for a file
LockServer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/LockServer.cpp.s
.PHONY : LockServer.cpp.s

gen-cpp/Locker.o: gen-cpp/Locker.cpp.o

.PHONY : gen-cpp/Locker.o

# target to build an object file
gen-cpp/Locker.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/Locker.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/Locker.cpp.o
.PHONY : gen-cpp/Locker.cpp.o

gen-cpp/Locker.i: gen-cpp/Locker.cpp.i

.PHONY : gen-cpp/Locker.i

# target to preprocess a source file
gen-cpp/Locker.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/Locker.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/Locker.cpp.i
.PHONY : gen-cpp/Locker.cpp.i

gen-cpp/Locker.s: gen-cpp/Locker.cpp.s

.PHONY : gen-cpp/Locker.s

# target to generate assembly for a file
gen-cpp/Locker.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/Locker.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/Locker.cpp.s
.PHONY : gen-cpp/Locker.cpp.s

gen-cpp/lock_constants.o: gen-cpp/lock_constants.cpp.o

.PHONY : gen-cpp/lock_constants.o

# target to build an object file
gen-cpp/lock_constants.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/lock_constants.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/lock_constants.cpp.o
.PHONY : gen-cpp/lock_constants.cpp.o

gen-cpp/lock_constants.i: gen-cpp/lock_constants.cpp.i

.PHONY : gen-cpp/lock_constants.i

# target to preprocess a source file
gen-cpp/lock_constants.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/lock_constants.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/lock_constants.cpp.i
.PHONY : gen-cpp/lock_constants.cpp.i

gen-cpp/lock_constants.s: gen-cpp/lock_constants.cpp.s

.PHONY : gen-cpp/lock_constants.s

# target to generate assembly for a file
gen-cpp/lock_constants.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/lock_constants.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/lock_constants.cpp.s
.PHONY : gen-cpp/lock_constants.cpp.s

gen-cpp/lock_types.o: gen-cpp/lock_types.cpp.o

.PHONY : gen-cpp/lock_types.o

# target to build an object file
gen-cpp/lock_types.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/lock_types.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/lock_types.cpp.o
.PHONY : gen-cpp/lock_types.cpp.o

gen-cpp/lock_types.i: gen-cpp/lock_types.cpp.i

.PHONY : gen-cpp/lock_types.i

# target to preprocess a source file
gen-cpp/lock_types.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/lock_types.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/lock_types.cpp.i
.PHONY : gen-cpp/lock_types.cpp.i

gen-cpp/lock_types.s: gen-cpp/lock_types.cpp.s

.PHONY : gen-cpp/lock_types.s

# target to generate assembly for a file
gen-cpp/lock_types.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/gen-cpp/lock_types.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/gen-cpp/lock_types.cpp.s
.PHONY : gen-cpp/lock_types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... server"
	@echo "... LockClient.o"
	@echo "... LockClient.i"
	@echo "... LockClient.s"
	@echo "... LockServer.o"
	@echo "... LockServer.i"
	@echo "... LockServer.s"
	@echo "... gen-cpp/Locker.o"
	@echo "... gen-cpp/Locker.i"
	@echo "... gen-cpp/Locker.s"
	@echo "... gen-cpp/lock_constants.o"
	@echo "... gen-cpp/lock_constants.i"
	@echo "... gen-cpp/lock_constants.s"
	@echo "... gen-cpp/lock_types.o"
	@echo "... gen-cpp/lock_types.i"
	@echo "... gen-cpp/lock_types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

