/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef lock_CONSTANTS_H
#define lock_CONSTANTS_H

#include "lock_types.h"



class lockConstants {
 public:
  lockConstants();

};

extern const lockConstants g_lock_constants;



#endif
